version: "3"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_WEB=/
      - _APP_URL=$SERVICE_FQDN_WEB
      - SERVICE_FQDN_WEB_3000
      - PAYLOAD_SECRET=${SERVICE_PASSWORD_WEB}
      - NEXT_PUBLIC_APP_URL=${SERVICE_URL_WEB}
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_URL=${REDIS_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
    deploy:
      replicas: 3
    labels:
      - "traefik.http.services.web.loadbalancer.server.port=3000"
