name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          for app in apps/*; do
            if [ -d "$app" ] && [ -f "$app/Dockerfile" ]; then
              app_name=$(basename "$app")
              echo "Building and pushing Docker image for $app_name"
              docker build \
                -t ghcr.io/${{ github.repository }}/$app_name:${{ github.sha }} \
                -t ghcr.io/${{ github.repository }}/$app_name:latest \
                -f $app/Dockerfile \
                .
              docker push ghcr.io/${{ github.repository }}/$app_name:${{ github.sha }}
              docker push ghcr.io/${{ github.repository }}/$app_name:latest
            elif [ -d "$app" ] && [ ! -f "$app/Dockerfile" ]; then
              echo "Skipping $app: No Dockerfile found"
            fi
          done
